dist: focal
language: cpp
sudo: required
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq

install:
  - |
    sudo apt-get install -y \
    libocct-* \
    libhdf5-dev \
    libboost-all-dev
    
script:
  - mkdir build && cd build
  - | 
    cmake -DHDF5_INCLUDE_DIR=/usr/include/hdf5/serial -DHDF5_LIBRARIES="/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.a;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.a;/usr/lib/x86_64-linux-gnu/libz.a;/usr/lib/x86_64-linux-gnu/libsz.a;/usr/lib/x86_64-linux-gnu/libaec.a;dl" .. \
    -DIFC_SUPPORT=Off \
    -DOCC_INCLUDE_DIR=/usr/include/opencascade \
    -DOCC_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu \
  - make -j2
  - make CTEST_OUTPUT_ON_FAILURE=1 test
